package com.agent47.springsecurityjwt.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.agent47.springsecurityjwt.model.User;
import com.agent47.springsecurityjwt.model.UserRequest;
import com.agent47.springsecurityjwt.model.UserResponse;
import com.agent47.springsecurityjwt.service.IUserService;
import com.agent47.springsecurityjwt.util.JwtUtil;

@RestController
@RequestMapping("/user")
public class UserController {

    @Autowired
    private IUserService userService;

    @Autowired
    private JwtUtil jwtUtil;

    @Autowired
    private AuthenticationManager authenticationManager;


    @PostMapping("/save")
    public ResponseEntity<String> saveUser(@RequestBody User user) {
        String body = null;
        try{
        Integer id = userService.saveUser(user);
        body = "User '" + id + "'saved";
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return ResponseEntity.ok(body);

    }
    @PostMapping("/login")
    public ResponseEntity<UserResponse> userLogin(@RequestBody UserRequest userRequest){
        // :validate username/password with database
        authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(userRequest.getUsername(),userRequest.getPassword()));

        String token = jwtUtil.generateToken(userRequest.getUsername());

        return ResponseEntity.ok(new UserResponse(token,"Success! Generated by JK"));
    }
    @GetMapping("/welcome")
    public String welcome(){
        return "u r welcome";
    }

}
